name: Build and push
on:
  workflow_call:
    inputs:
      name:
        description: 'Name'
        default: "John Doe"
        required: false
        type: string
jobs:
  jdk:
    name: Build
    uses: ./.github/workflows/graalvm-jdk.yaml
    secrets: inherit
  docker:
    name: Build
    uses: ./.github/workflows/traditional-build.yaml
    secrets: inherit
    